import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, Bot, BrainCircuit, Check, ChevronRight, ClipboardCheck, Cloud, Database, GraduationCap, LibraryBig, LineChart, MessageCircle, MonitorCheck, Sparkles, Target, Users, WandSparkles } from "lucide-react";
import TechStackMarquee from "./TechStackMarquee";
import TrustedOrganizationsMarquee from "./TrustedOrganizationsMarquee";
import UseCasesMarquee from "./UseCasesMarquee";

const challenges = [[Users,"Low Student Engagement","Difficulty keeping learners motivated"],[Target,"One-Size-Fits-All Learning","Generic content misses individual needs"],[ClipboardCheck,"Manual Assessments","Time-consuming evaluation and feedback"],[LineChart,"Lack of Real-time Insights","Limited visibility into performance"],[LibraryBig,"Content Overload","Hard to manage quality content"],[GraduationCap,"Skill Gap","Mismatch between learning and industry needs"]];
const solutions = [
  [BrainCircuit,"AI Learning Platform","/images/education/ai-learning-platform.png",["Adaptive Learning","Personalized Paths","Smart Content Delivery","Learning Recommendations","Progress Tracking"]],
  [ClipboardCheck,"Smart Assessment AI","/images/education/smart-assessment.png",["Auto Grading","Question Generation","Plagiarism Detection","Competency Mapping","Feedback Automation"]],
  [Bot,"AI Tutoring & Assistants","/images/education/ai-tutor.png",["24/7 AI Tutor","Doubt Resolution","Voice & Chat Support","Concept Explanation","Multilingual Support"]],
  [BarChart3,"Learning Analytics","/images/education/learning-analytics.png",["Performance Analytics","Predictive Insights","At-Risk Student Detection","Engagement Analytics","Custom Reports"]],
];
const useCases = [["K-12 Schools","/images/education/education-hero.png"],["Higher Education","/images/education/ai-learning-platform.png"],["Online Learning","/images/education/ai-tutor.png"],["Corporate Training","/images/education/learning-analytics.png"],["Coaching Institutes","/images/education/challenges.png"],["Skill Development","/images/education/ai-learning-platform.png"],["Language Learning","/images/education/ai-tutor.png"],["Test Preparation","/images/education/smart-assessment.png"],["Research & E-learning","/images/education/learning-analytics.png"]];
const features = ["Adaptive Learning Engine","Content Recommendation","Predictive Analytics","Intelligent Assessments","Automated Grading","Learning Path Optimization","Real-time Feedback","Scalable & Secure Platform"];
const workflow = [[Database,"Data Collection"],[LibraryBig,"Content Processing"],[Target,"Learning Path Generation"],[BrainCircuit,"AI Model Training"],[Sparkles,"Personalization"],[ClipboardCheck,"Assessment & Feedback"],[BarChart3,"Insights & Reports"]];

const Title = ({children}) => <h2 className="mb-5 text-center text-[11px] font-extrabold uppercase tracking-[.08em] text-[#0c327e]">{children}</h2>;

export default function EducationPage() {
  return <main className="bg-[#fcfdff] text-[#0b1d3a] dark:bg-[#071126] dark:text-white">
    <section className="relative overflow-hidden border-b border-blue-50">
      <Image src="/images/education/education-hero.png" alt="Student using an AI-powered learning platform" fill priority className="object-cover"/>
      <div className="absolute inset-0 bg-[linear-gradient(90deg,#fff_0%,rgba(255,255,255,.98)_37%,rgba(255,255,255,.18)_68%,rgba(255,255,255,.04)_100%)]"/>
      <div className="relative mx-auto grid min-h-[570px] max-w-[1440px] items-center gap-8 px-6 py-10 md:px-10 lg:grid-cols-[.72fr_1.28fr] lg:px-14">
        <div><span className="rounded bg-blue-50 px-3 py-1.5 text-[10px] font-bold text-[#075fd8]">EDUCATION & EDTECH SOLUTIONS</span><h1 className="mt-5 text-4xl font-extrabold leading-[1.08] tracking-[-.04em] sm:text-5xl lg:text-[52px]">AI-Powered Education,<span className="block text-[#1264d8]">EdTech Platforms & AI Learning Systems</span></h1><p className="mt-5 max-w-[520px] text-sm leading-7 text-slate-700">Transform learning experiences with AI-driven personalization, intelligent assessment, adaptive learning and advanced analytics for educators and institutions.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/contact" className="inline-flex items-center gap-2 rounded-md bg-[#1264d8] px-5 py-3 text-xs font-bold text-white">Book Free Consultation <ArrowRight size={14}/></Link></div></div>
      </div>
      <div className="industry-hero-icon-strip relative mx-auto grid max-w-[1200px] grid-cols-4 gap-3 px-6 pb-7 sm:grid-cols-8" style={{ position: "absolute", bottom: 0, left: "50%", zIndex: 20, width: "min(1200px, calc(100% - 3rem))", minHeight: 78, margin: 0, transform: "translateX(-50%)" }}>{[[BrainCircuit,"AI Learning"],[WandSparkles,"Smart Content"],[Target,"Adaptive Learning"],[ClipboardCheck,"Assessment AI"],[Users,"Student Analytics"],[MonitorCheck,"Virtual Tutoring"],[Cloud,"LMS Integration"],[Sparkles,"Learning Automation"]].map(([Icon,l])=><div key={l} className="text-center"><Icon size={20} className="mx-auto text-[#1264d8]"/><span className="mt-2 block text-[8px] font-semibold">{l}</span></div>)}</div>
    </section>

    <section className="mx-auto max-w-[1360px] px-6 py-5 md:px-10"><div className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><p className="text-center text-[10px] font-bold uppercase text-[#0c327e]">Trusted by leading education & EdTech organizations</p><TrustedOrganizationsMarquee organizations={["BYJU’S","unacademy","Vedantu","coursera","upGrad","WhiteHat Jr","KALVI","Pearson"]}/></div></section>

    <section className="mx-auto grid max-w-[1360px] gap-5 px-6 py-8 md:px-10 lg:grid-cols-[.8fr_1.2fr]"><div className="relative min-h-72 overflow-hidden rounded-xl"><Image src="/images/education/challenges.png" alt="Education industry challenges" fill className="object-cover"/></div><div><Title>Industry Challenges</Title><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{challenges.map(([Icon,t,c])=><div key={t} className="rounded-xl border border-slate-200 bg-white p-4"><Icon size={20} className="text-[#1264d8]"/><h3 className="mt-2 text-[10px] font-bold">{t}</h3><p className="mt-1 text-[8px] leading-4 text-slate-500">{c}</p></div>)}</div></div></section>

    <section className="mx-auto max-w-[1360px] px-6 py-8 md:px-10"><Title>Our AI-Powered Education Solutions</Title><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{solutions.map(([Icon,t,img,items])=><article key={t} className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="relative h-40"><Image src={img} alt={`${t} solution`} fill className="object-cover"/></div><div className="p-4"><div className="flex items-center gap-2"><Icon size={18} className="text-[#1264d8]"/><h3 className="text-xs font-bold">{t}</h3></div><ul className="mt-3 space-y-2 text-[8px] text-slate-600">{items.map(x=><li key={x} className="flex gap-2"><Check size={11} className="text-[#1264d8]"/>{x}</li>)}</ul><Link href="/contact" className="mt-4 inline-flex items-center gap-1 text-[9px] font-bold text-[#1264d8]">Explore Solution <ArrowRight size={11}/></Link></div></article>)}</div></section>

    <section className="mx-auto max-w-[1440px] px-6 py-8 md:px-10"><Title>Use Cases</Title><UseCasesMarquee useCases={useCases} label="Education use cases"/></section>

    <section className="mx-auto grid max-w-[1360px] gap-4 px-6 py-8 md:px-10 lg:grid-cols-[.55fr_1.8fr_.7fr]"><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-center text-[10px] font-bold uppercase text-[#0c327e]">AI Features</h2><ul className="mt-5 space-y-3">{features.map(x=><li key={x} className="flex gap-2 text-[8px]"><Check size={12} className="text-[#1264d8]"/>{x}</li>)}</ul></div><div><h2 className="mb-3 text-center text-[10px] font-bold uppercase text-[#0c327e]">Education Intelligence Dashboard</h2><div className="relative min-h-[340px] overflow-hidden rounded-xl bg-[#06172e]"><Image src="/images/consumer-technology/capabilities.png" alt="Education intelligence dashboard" fill className="object-cover"/></div></div><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-center text-[10px] font-bold uppercase text-[#0c327e]">AI Tutor Preview</h2><div className="mt-5 space-y-3"><div className="ml-auto max-w-[150px] rounded-xl bg-[#1264d8] p-3 text-[8px] text-white">Explain photosynthesis in simple words.</div><div className="rounded-xl bg-slate-100 p-3 text-[8px] leading-4 text-slate-600">Photosynthesis is how plants use sunlight, water and carbon dioxide to make food and release oxygen.</div><div className="flex items-center gap-2 rounded-full border px-3 py-2 text-[8px] text-slate-400">Ask anything... <MessageCircle size={12} className="ml-auto text-[#1264d8]"/></div></div></div></section>

    <section className="mx-auto grid max-w-[1360px] gap-4 px-6 pb-8 md:px-10"><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-center text-[10px] font-bold uppercase text-[#0c327e]">Technology Stack</h2><TechStackMarquee technologies={["Python","TensorFlow","PyTorch","OpenAI","AWS","Azure","Google Cloud","MongoDB","PostgreSQL","Redis","Docker","Kubernetes"]}/></div><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-center text-[10px] font-bold uppercase text-[#0c327e]">Our AI Learning Workflow</h2><div className="mt-7 grid grid-cols-4 gap-4 sm:grid-cols-7">{workflow.map(([Icon,l],i)=><div key={l} className="relative text-center">{i<6&&<ChevronRight size={13} className="absolute -right-2 top-5 hidden sm:block"/>}<span className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-blue-50 text-[#1264d8]"><Icon size={18}/></span><p className="mt-2 text-[7px] font-bold">{l}</p></div>)}</div></div></section>

    <section className="mx-auto max-w-[1360px] px-6 pb-10 md:px-10"><div className="relative min-h-[260px] overflow-hidden rounded-xl bg-[#06172e] text-white"><Image src="/images/education/education-cta.png" alt="AI education transformation" fill className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#06172e] via-[#06172e]/85 to-transparent"/><div className="relative max-w-sm p-6"><h2 className="text-2xl font-bold">Empower Learning. Enhance Outcomes. Build the Future with AI.</h2><p className="mt-3 text-[9px] leading-4 text-white/75">Create smarter, personalized and engaging learning experiences with Antellay AI solutions.</p><div className="mt-5 flex gap-2"><Link href="/contact" className="rounded bg-[#1264d8] px-4 py-2 text-[8px] font-bold">Book Free Consultation</Link></div></div></div></section>
  </main>;
}
