import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2, ChevronRight } from "lucide-react";
import TechStackMarquee from "./TechStackMarquee";
import TrustedOrganizationsMarquee from "./TrustedOrganizationsMarquee";
import UseCasesMarquee from "./UseCasesMarquee";

export default function IndustryAiPage({ config }) {
  const { accent, accentDark, eyebrow, title, highlight, description, hero, dashboardTitle, dashboardImage, smartImage, impactImage, ctaImage, ecosystemTitle = "Trusted Across the Ecosystem", solutionsTitle = "Our AI-Powered Solutions", stats, badges, logos, solutions, features, challenges, challengeImage, dashboardVariant, useCasesTitle = "Use Cases", technologies, workflow, useCases, useCaseImages, ctaTitle, ctaCopy } = config;
  const style = { "--accent": accent, "--accent-dark": accentDark };
  return <main style={style} className="bg-[#fbfdfc] text-[#10252f] dark:bg-[#071126] dark:text-white">
    <section className="relative overflow-hidden border-b border-slate-100">
      <div className="absolute inset-0"><Image src={hero} alt="" fill priority className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,#fff_0%,rgba(255,255,255,.97)_35%,rgba(255,255,255,.08)_72%)]"/></div>
      <div className="relative mx-auto grid max-w-[1440px] gap-8 px-6 py-12 md:px-10 lg:grid-cols-[.7fr_1.3fr] lg:px-14 lg:py-10">
        <div className="flex flex-col justify-center"><p className="mb-3 text-xs font-extrabold tracking-[.08em] text-[var(--accent)]">{eyebrow}</p><h1 className="text-4xl font-bold leading-[1.1] tracking-[-.035em] sm:text-5xl lg:text-[56px]">{title}<br/><span className="text-[var(--accent)]">{highlight}</span></h1><p className="mt-5 max-w-[500px] text-sm leading-6 text-slate-700">{description}</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/contact" className="inline-flex items-center gap-2 rounded-md bg-[var(--accent)] px-5 py-3 text-xs font-bold text-white transition hover:brightness-90">Book Free Consultation <ArrowRight size={14}/></Link></div><div className={`industry-hero-icon-strip mt-8 grid grid-cols-2 gap-3 ${badges.length > 4 ? "sm:grid-cols-3" : "sm:grid-cols-4"}`} style={{ position: "absolute", bottom: 0, left: "50%", zIndex: 20, width: "min(1200px, calc(100% - 3rem))", minHeight: 78, margin: 0, transform: "translateX(-50%)" }}>{badges.map(({icon:Icon,label})=><div key={label} className="flex items-center gap-2 text-[9px] font-semibold"><Icon size={20} className="shrink-0 text-[var(--accent)]"/>{label}</div>)}</div></div>
      </div>
    </section>

    <section className="mx-auto max-w-[1440px] px-6 py-4 md:px-10 lg:px-8"><div className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><p className="text-center text-[10px] font-bold uppercase">{ecosystemTitle} <span className="ml-2 inline-block h-px w-10 align-middle bg-[var(--accent)]"/></p><TrustedOrganizationsMarquee organizations={logos}/></div></section>

    {challenges && <section className="mx-auto grid max-w-[1440px] gap-4 px-6 py-5 md:px-10 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div className="relative min-h-72 overflow-hidden rounded-xl"><Image src={challengeImage || hero} alt="Industry infrastructure challenges" fill className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,transparent,rgba(4,35,55,.18))]"/></div><div><h2 className="mb-4 text-center text-xs font-bold uppercase">Industry Challenges</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{challenges.map(({icon:Icon,title,copy})=><div key={title} className="min-h-28 rounded-xl border border-slate-100 bg-white p-4 shadow-sm"><Icon size={22} className="mb-2" style={{color:accent}}/><h3 className="text-[10px] font-bold">{title}</h3><p className="mt-1 text-[8px] leading-3.5 text-slate-500">{copy}</p></div>)}</div></div></section>}

    <section className="mx-auto max-w-[1440px] px-6 py-5 md:px-10 lg:px-8"><h2 className="mb-5 text-center text-sm font-bold uppercase">{solutionsTitle} <span className="ml-2 inline-block h-px w-10 align-middle bg-[var(--accent)]"/></h2><div className="grid gap-4 lg:grid-cols-3">{solutions.map(({icon:Icon,title,items,image},i)=><article key={title} className="group relative min-h-72 overflow-hidden rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><Image src={image || hero} alt={`${title} industry solution`} fill className={`object-cover transition duration-500 group-hover:scale-105 ${i === 1 ? "object-center" : i === 2 ? "object-right" : "object-left"}`}/><div className="absolute inset-0 bg-gradient-to-r from-white/98 via-white/85 to-white/5"/><div className="relative"><span className="grid h-10 w-10 place-items-center rounded-full bg-white shadow" style={{color:accent}}><Icon size={22}/></span><h3 className="mt-3 text-sm font-bold">{title}</h3><ul className="mt-4 space-y-3 text-[10px] text-slate-700">{items.map(x=><li key={x} className="flex gap-2"><CheckCircle2 size={13} style={{color:accent}}/>{x}</li>)}</ul></div></article>)}</div></section>

    <section className={`mx-auto grid max-w-[1440px] gap-4 px-6 py-5 md:px-10 lg:px-8 ${dashboardVariant === "agriculture" ? "lg:grid-cols-[1.35fr_.65fr]" : "lg:grid-cols-[.65fr_1.35fr]"}`}>
      {dashboardVariant !== "agriculture" && <div className="rounded-xl border border-slate-100 bg-white p-5"><h2 className="text-xs font-bold uppercase">AI Features</h2><div className="mt-4 grid grid-cols-2 gap-3">{features.map(({icon:Icon,label})=><div key={label} className="flex items-center gap-2 text-[9px] font-semibold"><span className="grid h-7 w-7 place-items-center rounded bg-slate-50" style={{color:accent}}><Icon size={15}/></span>{label}</div>)}</div></div>}
      <div><h2 className="mb-3 text-center text-xs font-bold uppercase">{dashboardTitle}</h2><div className="relative min-h-[340px] overflow-hidden rounded-xl bg-slate-950"><Image src={hero} alt="Interactive industry dashboard" fill className="object-cover opacity-50"/><div className="absolute inset-4 rounded-lg border border-white/10 bg-slate-950/72 p-4 text-white"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{stats.map(([v,l])=><div key={l} className="rounded bg-white/5 p-3"><b className="text-xl" style={{color:accent}}>{v}</b><span className="block text-[8px] text-white/60">{l}</span></div>)}</div><div className="mt-4 grid grid-cols-[1.2fr_.8fr] gap-3"><div className="relative h-32 overflow-hidden rounded"><Image src={hero} alt="" fill className="object-cover"/></div><div className="rounded bg-white/5 p-3"><p className="text-[8px] text-white/60">Live Performance</p><b className="mt-2 block text-2xl" style={{color:accent}}>{stats[2][0]}</b><svg viewBox="0 0 180 55" className="mt-3 w-full" fill="none"><path d="M0 45 C30 38 35 15 65 28 S110 9 140 22 S165 12 180 8" stroke={accent} strokeWidth="3"/></svg></div></div></div></div></div>
      {dashboardVariant === "agriculture" && <div><h2 className="mb-3 text-center text-xs font-bold uppercase">Smart Irrigation</h2><div className="relative min-h-[340px] overflow-hidden rounded-xl"><Image src={smartImage || hero} alt="Smart irrigation system" fill className="object-cover"/><div className="absolute inset-x-4 bottom-4 rounded-lg bg-slate-950/78 p-4 text-white backdrop-blur"><h3 className="text-sm font-bold">Smart Irrigation</h3><p className="mt-1 text-[9px] leading-4 text-white/70">Automated irrigation based on real-time soil moisture and weather conditions.</p></div></div></div>}
    </section>

    <section className="mx-auto grid max-w-[1440px] gap-5 px-6 py-5 md:px-10 lg:px-8"><div className="rounded-xl border border-slate-100 bg-white p-5"><h2 className="text-center text-xs font-bold uppercase">Technologies We Use</h2><TechStackMarquee technologies={technologies}/></div><div className="rounded-xl border border-slate-100 bg-white p-5"><h2 className="text-center text-xs font-bold uppercase">Our Workflow</h2><div className="mt-6 grid grid-cols-3 gap-5 sm:grid-cols-6">{workflow.map(({icon:Icon,label},i)=><div key={label} className="relative text-center">{i<5&&<ChevronRight className="absolute -right-3 top-5 hidden sm:block" size={14} style={{color:accent}}/>}<span className="mx-auto grid h-11 w-11 place-items-center rounded-full bg-slate-50" style={{color:accent}}><Icon size={22}/></span><p className="mt-2 text-[8px] font-bold">{label}</p></div>)}</div></div></section>

    <section className="mx-auto max-w-[1440px] px-6 py-8 md:px-10 lg:px-8"><h2 className="mb-4 text-center text-xs font-bold uppercase">{useCasesTitle}</h2><UseCasesMarquee useCases={useCases.map((name, index) => [name, useCaseImages?.[index] || hero])} label={useCasesTitle}/></section>

    <section className="mx-auto max-w-[1440px] px-6 pb-4 pt-5 md:px-10 lg:px-8"><div className="relative overflow-hidden rounded-xl bg-slate-950 px-7 py-8 text-white"><Image src={ctaImage || hero} alt="Smart connected agriculture" fill className="object-cover opacity-45"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/75 to-transparent"/><div className="relative max-w-xl"><h2 className="text-2xl font-bold">{ctaTitle}</h2><p className="mt-2 text-[10px] leading-5 text-white/80">{ctaCopy}</p><div className="mt-5 flex gap-3"><Link href="/contact" className="rounded px-4 py-2.5 text-[9px] font-bold text-white" style={{backgroundColor:accent}}>Book Free Consultation</Link></div></div></div></section>
  </main>;
}
